### ISSUE TITLE
AttributeError: 'PR' object has no attribute 'S_dep_g'

### ISSUE THREAD

**Issue by BenPortner** [CalebBell/thermo#117]
Dear @CalebBell,

@yoelcortes sent me (related to [this issue](https://github.com/BioSTEAMDevelopmentGroup/thermosteam/issues/69)) 😃
To determine the power of a compressor, I am trying to calculate the entropy of hydrogen at 350 bar. However, for some reason it fails:

```python 
from thermo.eos import PR
PR(T=298.15, P=20e5, Tc=33.2, Pc=1296960.0, omega=-0.22).S_dep_g # this works
PR(T=298.15, P=350e5, Tc=33.2, Pc=1296960.0, omega=-0.22).S_dep_g # AttributeError: 'PR' object has no attribute 'S_dep_g' 
``` 

I am working with thermo version 0.2.21. Any idea what I am doing wrong?

Thank you.
Ben

**Comment by CalebBell** [comment]
Hi Ben!

What is happening here is that at sufficiently high pressures, hydrogen is becoming liquid-like. For pure components, there are two cases:

* Both a liquid-like and gas-like volume root are available. Use the one with the lowest Gibbs free energy, i.e. G_dep_l or G_dep_g.
* There is only one volume root available. Use it.

The Peng-Robinson equation of state itself doesn't know the difference between a gas and a liquid, it just knows that there can be one or two solutions. It is easy to say one is gas and the other is liquid when there are two solutions, but when there is only one, the method described [here](https://chemicals.readthedocs.io/chemicals.utils.html#chemicals.utils.phase_identification_parameter) is used. 


Sincerely,
Caleb
